import type { PrintPreset } from "../image-pipeline";
import { INK_LIBRARY } from "./inks";
import { PAPER_PROFILES } from "./papers";

export const DEFAULT_PRESETS = [
  {
    id: "soft-paper",
    name: "Soft Paper",
    description: "柔和低对比，纸张颗粒明显，适合日常照片。",
    separationMode: "expressive",
    inks: [INK_LIBRARY.deepBlue],
    paper: PAPER_PROFILES.softPaper,
    halftone: {
      enabled: true,
      dotShape: "soft-round",
      dotSize: 1.4,
      spacing: 7,
      angle: 30,
      contrast: 0.48,
    },
    grain: {
      amount: 0.42,
      scale: 1.2,
      softness: 0.7,
    },
    misregistration: {
      amount: 0,
      randomize: false,
    },
    tone: {
      brightness: 0.04,
      contrast: -0.12,
      saturation: -0.16,
      posterizeLevels: 7,
    },
  },
  {
    id: "riso-bloom",
    name: "Riso Bloom",
    description: "基础色分层叠印，多层彩色网点带轻微错版。",
    separationMode: "expressive",
    inks: [
      { ...INK_LIBRARY.vermilion, angle: 0 },
      { ...INK_LIBRARY.peacock, angle: 0 },
      { ...INK_LIBRARY.mustard, angle: 0 },
    ],
    paper: PAPER_PROFILES.softPaper,
    halftone: {
      enabled: true,
      dotShape: "rough",
      dotSize: 2.2,
      spacing: 8,
      angle: 18,
      contrast: 0.62,
    },
    grain: {
      amount: 0.34,
      scale: 1.1,
      softness: 0.48,
    },
    misregistration: {
      amount: 2,
      randomize: false,
    },
    tone: {
      brightness: 0.02,
      contrast: 0.08,
      saturation: 0.16,
      posterizeLevels: 5,
    },
  },
  {
    id: "real-color-print",
    name: "现实彩印",
    description: "严格 CMYK 分色后重组，优先接近原图颜色。",
    separationMode: "process-cmyk",
    inks: [
      { ...INK_LIBRARY.processCyan, color: "#00ffff", opacity: 1, offsetX: 0, offsetY: 0 },
      { ...INK_LIBRARY.processMagenta, color: "#ff00ff", opacity: 1, offsetX: 0, offsetY: 0 },
      { ...INK_LIBRARY.processYellow, color: "#ffff00", opacity: 1, offsetX: 0, offsetY: 0 },
      { ...INK_LIBRARY.black, color: "#000000", opacity: 1, offsetX: 0, offsetY: 0 },
    ],
    paper: PAPER_PROFILES.photoPaper,
    halftone: {
      enabled: true,
      dotShape: "round",
      dotSize: 4,
      spacing: 4,
      angle: 15,
      contrast: 0.65,
    },
    grain: {
      amount: 0.02,
      scale: 0.8,
      softness: 0.65,
    },
    misregistration: {
      amount: 0,
      randomize: false,
    },
    tone: {
      brightness: 0,
      contrast: 0,
      saturation: 0,
      posterizeLevels: 256,
    },
  },
  {
    id: "faded-color-print",
    name: "褪色彩印",
    description: "颜色偏淡、轻微失真和褪色的 CMYK 风格彩印。",
    separationMode: "expressive",
    inks: [
      INK_LIBRARY.processCyan,
      INK_LIBRARY.processMagenta,
      INK_LIBRARY.processYellow,
      { ...INK_LIBRARY.black, opacity: 0.62, offsetX: 0.1, offsetY: -0.1 },
    ],
    paper: PAPER_PROFILES.coolWhite,
    halftone: {
      enabled: true,
      dotShape: "round",
      dotSize: 1.55,
      spacing: 5,
      angle: 15,
      contrast: 0.55,
    },
    grain: {
      amount: 0.24,
      scale: 1,
      softness: 0.5,
    },
    misregistration: {
      amount: 0.8,
      randomize: true,
    },
    tone: {
      brightness: 0.02,
      contrast: 0.02,
      saturation: 0.02,
      posterizeLevels: 8,
    },
  },
  {
    id: "newspaper-dot",
    name: "Newspaper Dot",
    description: "明显网点和新闻纸底色，细节损失更强。",
    separationMode: "expressive",
    inks: [INK_LIBRARY.black],
    paper: PAPER_PROFILES.newsprint,
    halftone: {
      enabled: true,
      dotShape: "square",
      dotSize: 2.8,
      spacing: 6,
      angle: 45,
      contrast: 0.75,
    },
    grain: {
      amount: 0.55,
      scale: 1.4,
      softness: 0.35,
    },
    misregistration: {
      amount: 0,
      randomize: false,
    },
    tone: {
      brightness: -0.02,
      contrast: 0.22,
      saturation: -0.7,
      posterizeLevels: 4,
    },
  },
  {
    id: "mono-grain",
    name: "Mono Grain",
    description: "单色通道压成近单色颗粒，影印感更克制。",
    separationMode: "expressive",
    inks: [INK_LIBRARY.moss],
    paper: PAPER_PROFILES.recycled,
    halftone: {
      enabled: false,
      dotShape: "rough",
      dotSize: 1,
      spacing: 10,
      angle: 45,
      contrast: 0.38,
    },
    grain: {
      amount: 0.72,
      scale: 1.8,
      softness: 0.24,
    },
    misregistration: {
      amount: 0,
      randomize: false,
    },
    tone: {
      brightness: 0,
      contrast: 0.16,
      saturation: -0.8,
      posterizeLevels: 6,
    },
  },
  {
    id: "warm-poster",
    name: "Warm Poster",
    description: "暖色基础油墨叠印，色块和网点更强。",
    separationMode: "expressive",
    inks: [
      { ...INK_LIBRARY.vermilion, angle: 0 },
      { ...INK_LIBRARY.mustard, angle: 0 },
      { ...INK_LIBRARY.black, angle: 0 },
    ],
    paper: PAPER_PROFILES.warmPoster,
    halftone: {
      enabled: true,
      dotShape: "soft-round",
      dotSize: 2,
      spacing: 9,
      angle: 60,
      contrast: 0.68,
    },
    grain: {
      amount: 0.4,
      scale: 1.05,
      softness: 0.42,
    },
    misregistration: {
      amount: 1.5,
      randomize: false,
    },
    tone: {
      brightness: 0.04,
      contrast: 0.18,
      saturation: 0.1,
      posterizeLevels: 5,
    },
  },
] satisfies PrintPreset[];
