import type { InkLayer } from "../image-pipeline";

export const INK_LIBRARY = {
  black: {
    id: "ink-black",
    name: "炭黑",
    color: "#1f2223",
    opacity: 0.9,
    angle: 45,
    offsetX: 0,
    offsetY: 0,
  },
  processCyan: {
    id: "ink-process-cyan",
    name: "印刷青",
    color: "#0096b7",
    opacity: 0.74,
    angle: 15,
    offsetX: -0.4,
    offsetY: 0.2,
  },
  processMagenta: {
    id: "ink-process-magenta",
    name: "印刷品红",
    color: "#c83277",
    opacity: 0.7,
    angle: 75,
    offsetX: 0.4,
    offsetY: -0.2,
  },
  processYellow: {
    id: "ink-process-yellow",
    name: "印刷黄",
    color: "#e7bd16",
    opacity: 0.64,
    angle: 0,
    offsetX: 0.2,
    offsetY: 0.4,
  },
  deepBlue: {
    id: "ink-deep-blue",
    name: "深蓝",
    color: "#1c4769",
    opacity: 0.78,
    angle: 15,
    offsetX: -1,
    offsetY: 1,
  },
  vermilion: {
    id: "ink-vermilion",
    name: "朱红",
    color: "#d84a24",
    opacity: 0.82,
    angle: 75,
    offsetX: 1,
    offsetY: -1,
  },
  peacock: {
    id: "ink-peacock",
    name: "孔雀蓝",
    color: "#217b82",
    opacity: 0.72,
    angle: 30,
    offsetX: -2,
    offsetY: 0,
  },
  mustard: {
    id: "ink-mustard",
    name: "芥末黄",
    color: "#d8a526",
    opacity: 0.72,
    angle: 0,
    offsetX: 2,
    offsetY: 1,
  },
  moss: {
    id: "ink-moss",
    name: "墨绿",
    color: "#4c6a42",
    opacity: 0.74,
    angle: 60,
    offsetX: 0,
    offsetY: 2,
  },
} satisfies Record<string, InkLayer>;
